name = "The Lands Beyond"
author = "Someone"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "16065c053939648d1921eec549e8d596067b0f3d2da4619d663fc78d2999da2d"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
