name = "The Lands Beyond"
author = "Someone"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "accb72f03223f08443d01b7f29d5a328e4441ef9b71d1bbae4ecb349bb45f60a"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
