name = "The Lands Beyond"
author = "Someone"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5adb67a38205d92cfa8dfe56cadda61857ba8b493908be41eb0a260a2ef7135b"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
