name = "The Lands Beyond"
author = "Someone"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3f97c6651fd155777dfd1c9cf2419866f9d99645d5680e441cbceee1bce732e6"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
