name = "The Lands Beyond"
author = "Someone"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5fa45080fde122f329014d204b4892f136df6871112cfb0248cd89775cc0a2e4"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
