name = "The Lands Beyond"
author = "Someone"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cb8ee893025ac8b1b7b26489c452adb1ac4639081aef60e2526f77b27bd0f03b"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
